### ISSUE TITLE
where is save/debug/command.txt

### ISSUE THREAD

**Issue by NaJeehye** [yashkant/sam-textvqa#4]
# Q1. What should I do to solve the problem?
after I finish all settings, I want to try pretrained-models.
So, I ran the below code
`
python train.py \
--config configs/train-tvqa_stvqa-eval-tvqa-c3.yml \
--pretrained_eval data/pretrained-models/best_model.tar
`
I get the error message 
![image](https://user-images.githubusercontent.com/41455920/99793471-15f87980-2b6c-11eb-9397-278bc11e6315.png)
(click the photo, and you see the bigger photo.)

# Q2. What should I do to solve the problem?
## How can I get "wiki.en.bin"?
So, I ran the below code.
`
python train.py \
--config configs/train-stvqa-eval-stvqa-c3.yml \
--tag debug
`
and I have trouble with fastText.
![image](https://user-images.githubusercontent.com/41455920/99804206-fb2f0080-2b7d-11eb-9381-ce13df4bfd9b.png)

![image](https://user-images.githubusercontent.com/41455920/99803443-cec6b480-2b7c-11eb-8461-bbb7e848d354.png)

I and my colleague have to trouble with Q2!
(Warning : `load_model` does not return WordVectorModel or SupervisedModel any more, but a `FastText` object which is very similar.)

**Comment by jonpoveda** [comment]
You can fix Q1 by creating the folder manually, or code to create the file if it doesn't exist.
About Q2, you need to download the vocabulary from torchtext before loading the model.

Once you fix that, you may find another error message, which I'm trying to fix by now.

**Comment by yashkant** [comment]
Hi @NaJeehye and @jonpoveda, 

The Q1 seems to be a trivial fix, `command.txt` is created when you run the code.
For Q2 (regarding Fastttext), please see the instructions here: https://github.com/facebookresearch/mmf/tree/v0.3#troubleshootingfaqs
