### ISSUE TITLE
Question about data files from Dropbox link

### ISSUE THREAD

**Issue by JayZhu0104** [yashkant/sam-textvqa#5]
Hi!
Is the obj.lmdb file in the Dropbox link the feature extracted by the ResNeXT-152 based Faster R-CNN model?And the ocr.Imdb file feature extracted by the Google OCR?

**Comment by yashkant** [comment]
Hi, 

Yes, those features are extracted from ResNeXT-152 Faster R-CNN. Google OCR only provides bounding-boxes, which are used to extract features from the object detection model.

**Comment by JayZhu0104** [comment]
Hi, I'm sorry to bother you again.
When I ran the code you provided, there was an error indicating that there was no 'tvqa_ {}_spat_cache_reset.pkl' file, which I did not find in the Dropbox link.
Could you tell me how to get this document?
![image](https://user-images.githubusercontent.com/40751213/101429524-1e0f3200-393e-11eb-99c5-24843ab5f80c.png)

![image](https://user-images.githubusercontent.com/40751213/101429508-12bc0680-393e-11eb-83e4-62290602d5dd.png)

**Comment by JayZhu0104** [comment]
@yashkant 
Sorry to bother you again. I have another question.
I want to know whether the ". LMDB" files (such as "tvqa_test_obj.lmdb") store the feature vector of fc6 or fc7
