### ISSUE TITLE
Visualization results from prediction

### ISSUE THREAD

**Issue by HenryJunW** [yashkant/sam-textvqa#7]
Hello, good work, thanks for open source your code! Right now I want to visualize the question, image and predicted answer. I am wondering whether there is any function/demo file which takes in an image and gives out the prediction for that image. Thanks.

**Comment by yashkant** [comment]
Hi @HenryJunW,

Thank you for your interest in our work! 

I am afraid I do not have any visualization code in this repository, but you can build a simple HTML file using the predictions of SAM that I have shared [here](https://github.com/yashkant/sam-textvqa/issues/2#issuecomment-717685601).

**Comment by HenryJunW** [comment]
Thanks for your reply!
