### ISSUE TITLE
ModuleNotFoundError: No module named 'sam.phoc.cphoc'

### ISSUE THREAD

**Issue by daaidouya** [yashkant/sam-textvqa#8]
after I configure the environment, the code ran with an error:
`ModuleNotFoundError: No module named 'sam.phoc.cphoc'`
how can i run the code in windows? thanks!

**Comment by yashkant** [comment]
Hi @daaituzi,

Sorry for the delay. 

Please take a look at this repository for PHOC related issues, I had simply followed the instructions to install it -- 
https://github.com/facebookresearch/mmf/tree/project/m4c/projects/M4C

Hope this helps!
